apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "secrets-viewer.fullname" . }}
  namespace: {{ include "secrets-viewer.namespace" . }}
  labels:
    {{- include "secrets-viewer.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "secrets-viewer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "secrets-viewer.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "secrets-viewer.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: secrets-viewer
          image: {{ include "secrets-viewer.image" . }}
          imagePullPolicy: {{ include "secrets-viewer.imagePullPolicy" . }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "secrets-viewer.fullname" . }}-config
            - secretRef:
                name: {{ include "secrets-viewer.fullname" . }}-secrets
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          securityContext:
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
