{{- if not .Values.externalSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secrets-viewer.fullname" . }}-secrets
  namespace: {{ include "secrets-viewer.namespace" . }}
  labels:
    {{- include "secrets-viewer.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
